POST http://localhost:3000/register/
Content-Type: application/json

{
    "name":"shivaram9398",
    "username": "shiv",
    "password":"123456789",
    "age":30
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"shiv",
    "password":"123456789"
}

###
GET http://localhost:3000/highest_runs/?limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXYiLCJpYXQiOjE3MTY2NTU3MDd9.Anm-MWpfNrcLgZ2evarADBBitd8xLZPBdeyKb3NOSns

###
GET http://localhost:3000/highest_strikerate/?limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXYiLCJpYXQiOjE3MTY2NTU3MDd9.Anm-MWpfNrcLgZ2evarADBBitd8xLZPBdeyKb3NOSns